events {

}

http {
    client_max_body_size 10M;

    # ------ Production ------

    # Main domain for back end
    server {
        listen 80;
        server_name route.noor.uz;

        location /.well-known/acme-challenge {
            root /usr/share/nginx/html/challenge;
        }
    }
}